/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.autobazar;

import com.sun.xml.internal.bind.v2.model.impl.ModelBuilder;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    private MySqlInzeratDao inzeratDao = new MySqlInzeratDao();
    private MySqlPouzivatelDao pouzivatelDao = new MySqlPouzivatelDao();
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        autobazarDesktopPane = new javax.swing.JDesktopPane();
        vyhladavaciPanel = new javax.swing.JPanel();
        vyhladavanieNadpis = new javax.swing.JLabel();
        znackaBox = new javax.swing.JComboBox();
        modelBox = new javax.swing.JComboBox();
        vyhladajButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        znackaLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        rocnikOdBox = new javax.swing.JComboBox();
        rocnikDoBox = new javax.swing.JComboBox();
        rocnikOdLabel = new javax.swing.JLabel();
        rocnikDoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inzeratyList = new javax.swing.JList();
        topPanel = new javax.swing.JPanel();
        prihlasenieButton = new javax.swing.JButton();
        registraciaButton = new javax.swing.JButton();
        languageLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datumTextField = new javax.swing.JTextField();
        autobazarPanel = new javax.swing.JPanel();
        nadpisLabel = new javax.swing.JLabel();
        pridatInzeratButton = new javax.swing.JButton();
        podnadpisLabel = new javax.swing.JLabel();
        downPanel = new javax.swing.JPanel();
        copyrightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        autobazarDesktopPane.setBackground(new java.awt.Color(57, 74, 133));
        autobazarDesktopPane.setToolTipText("");
        autobazarDesktopPane.setPreferredSize(new java.awt.Dimension(1024, 700));

        vyhladavanieNadpis.setText("Vyhladavanie");

        znackaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Audi", "Skoda", "Volkswagen", "Volvo" }));
        znackaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                znackaBoxActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, znackaBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), modelBox, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        modelBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                modelBoxPropertyChange(evt);
            }
        });

        vyhladajButton.setText("Vyhladat");
        vyhladajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyhladajButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Rozsirene vyhladavanie");

        znackaLabel.setText("Znacka");

        modelLabel.setText("Model");

        rocnikOdBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        rocnikOdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rocnikOdBoxActionPerformed(evt);
            }
        });

        rocnikDoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        rocnikOdLabel.setText("Rocnik od");

        rocnikDoLabel.setText("Rocnik do");

        javax.swing.GroupLayout vyhladavaciPanelLayout = new javax.swing.GroupLayout(vyhladavaciPanel);
        vyhladavaciPanel.setLayout(vyhladavaciPanelLayout);
        vyhladavaciPanelLayout.setHorizontalGroup(
            vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyhladavaciPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vyhladavaciPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vyhladavanieNadpis)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vyhladavaciPanelLayout.createSequentialGroup()
                        .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(vyhladavaciPanelLayout.createSequentialGroup()
                                .addComponent(znackaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(znackaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vyhladavaciPanelLayout.createSequentialGroup()
                                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelLabel)
                                    .addComponent(rocnikOdLabel)
                                    .addComponent(rocnikDoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rocnikOdBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modelBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rocnikDoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 79, 79))))
            .addGroup(vyhladavaciPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vyhladajButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vyhladavaciPanelLayout.setVerticalGroup(
            vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyhladavaciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vyhladavanieNadpis)
                .addGap(18, 18, 18)
                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(znackaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(znackaLabel))
                .addGap(33, 33, 33)
                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel))
                .addGap(39, 39, 39)
                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rocnikOdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rocnikOdLabel))
                .addGap(33, 33, 33)
                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rocnikDoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rocnikDoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(vyhladavaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(vyhladajButton))
                .addGap(38, 38, 38))
        );

        inzeratyList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        inzeratyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inzeratyListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inzeratyList);

        prihlasenieButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/panacik.png"))); // NOI18N
        prihlasenieButton.setText("Prihlasenie");
        prihlasenieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasenieButtonActionPerformed(evt);
            }
        });

        registraciaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/panacik.png"))); // NOI18N
        registraciaButton.setText("Registracia");
        registraciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraciaButtonActionPerformed(evt);
            }
        });

        languageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/sk.png"))); // NOI18N
        languageLabel.setText("SK");

        jLabel3.setText("Dobry den, dnes je");

        datumTextField.setText("datum");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registraciaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prihlasenieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(languageLabel)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(prihlasenieButton)
                .addComponent(registraciaButton)
                .addComponent(languageLabel)
                .addComponent(jLabel3)
                .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        autobazarPanel.setBackground(new java.awt.Color(57, 74, 133));

        nadpisLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nadpisLabel.setForeground(new java.awt.Color(255, 255, 255));
        nadpisLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/A.png"))); // NOI18N
        nadpisLabel.setText("utobazar.sk");

        pridatInzeratButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pridatInzeratButton.setText("Pridat inzerat");

        podnadpisLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        podnadpisLabel.setForeground(new java.awt.Color(255, 255, 255));
        podnadpisLabel.setText("najlepsi autobazar na Slovensku");

        javax.swing.GroupLayout autobazarPanelLayout = new javax.swing.GroupLayout(autobazarPanel);
        autobazarPanel.setLayout(autobazarPanelLayout);
        autobazarPanelLayout.setHorizontalGroup(
            autobazarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autobazarPanelLayout.createSequentialGroup()
                .addGroup(autobazarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(autobazarPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nadpisLabel))
                    .addGroup(autobazarPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(podnadpisLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addComponent(pridatInzeratButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        autobazarPanelLayout.setVerticalGroup(
            autobazarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autobazarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nadpisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(podnadpisLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autobazarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pridatInzeratButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        copyrightLabel.setText("Copyright © 2015 Autobazar SK");

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copyrightLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(copyrightLabel))
        );

        javax.swing.GroupLayout autobazarDesktopPaneLayout = new javax.swing.GroupLayout(autobazarDesktopPane);
        autobazarDesktopPane.setLayout(autobazarDesktopPaneLayout);
        autobazarDesktopPaneLayout.setHorizontalGroup(
            autobazarDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autobazarDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autobazarDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autobazarDesktopPaneLayout.createSequentialGroup()
                        .addComponent(vyhladavaciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(downPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autobazarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        autobazarDesktopPaneLayout.setVerticalGroup(
            autobazarDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autobazarDesktopPaneLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autobazarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autobazarDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(vyhladavaciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autobazarDesktopPane.setLayer(vyhladavaciPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        autobazarDesktopPane.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        autobazarDesktopPane.setLayer(topPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        autobazarDesktopPane.setLayer(autobazarPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        autobazarDesktopPane.setLayer(downPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(autobazarDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(autobazarDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void znackaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_znackaBoxActionPerformed
        if(znackaBox.getSelectedIndex()==0){
            String[] items = {"A4", "A6", "Q7"};            
            modelBox.setModel(new DefaultComboBoxModel(items));
        }
        
        if(znackaBox.getSelectedIndex()==1){
            String[] items = {"Fabia", "Octavia", "Felicia"};            
            modelBox.setModel(new DefaultComboBoxModel(items));
        }
        if(znackaBox.getSelectedIndex()==2){
            String[] items = {"Polo", "Golf", "Passat"};            
            modelBox.setModel(new DefaultComboBoxModel(items));
        }
        if(znackaBox.getSelectedIndex()==3){
            String[] items = {"S60", "XC70", "XC90"};            
            modelBox.setModel(new DefaultComboBoxModel(items));
        }
    }//GEN-LAST:event_znackaBoxActionPerformed

    
    private void vyhladajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyhladajButtonActionPerformed
        List<Inzerat> inzeraty = inzeratDao.vyhladaj(znackaBox.getSelectedItem().toString(), modelBox.getSelectedItem().toString(), 
                rocnikOdBox.getSelectedItem().toString(), rocnikDoBox.getSelectedItem().toString());
        VyhladavacInzeratovForm v = new VyhladavacInzeratovForm(this, true,inzeraty);
        v.setVisible(true);
    }//GEN-LAST:event_vyhladajButtonActionPerformed

    private void inzeratyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inzeratyListMouseClicked
       if(evt.getClickCount()==2){
            Inzerat inzerat = (Inzerat) inzeratyList.getSelectedValue();
            
            InzeratForm inzeratform = new InzeratForm(this, true, inzerat);
            inzeratform.setVisible(true);
            
            refresh();
        }
    }//GEN-LAST:event_inzeratyListMouseClicked

    private void modelBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_modelBoxPropertyChange
       
    }//GEN-LAST:event_modelBoxPropertyChange

    private void rocnikOdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rocnikOdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rocnikOdBoxActionPerformed

    private void registraciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraciaButtonActionPerformed
        RegistraciaForm rf = new RegistraciaForm(this, true);
        rf.setVisible(true);
    }//GEN-LAST:event_registraciaButtonActionPerformed

    private void prihlasenieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasenieButtonActionPerformed
        PrihlasenieForm pf = new PrihlasenieForm(this, true);
        pf.setVisible(true);
    }//GEN-LAST:event_prihlasenieButtonActionPerformed

    private void refresh() {
        List<Inzerat> inzeraty = inzeratDao.dajVsetky();
        inzeratyList.setListData(inzeraty.toArray());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane autobazarDesktopPane;
    private javax.swing.JPanel autobazarPanel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JPanel downPanel;
    private javax.swing.JList inzeratyList;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JComboBox modelBox;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel nadpisLabel;
    private javax.swing.JLabel podnadpisLabel;
    private javax.swing.JButton pridatInzeratButton;
    private javax.swing.JButton prihlasenieButton;
    private javax.swing.JButton registraciaButton;
    private javax.swing.JComboBox rocnikDoBox;
    private javax.swing.JLabel rocnikDoLabel;
    private javax.swing.JComboBox rocnikOdBox;
    private javax.swing.JLabel rocnikOdLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton vyhladajButton;
    private javax.swing.JPanel vyhladavaciPanel;
    private javax.swing.JLabel vyhladavanieNadpis;
    private javax.swing.JComboBox znackaBox;
    private javax.swing.JLabel znackaLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
